spring:
  application:
    name: gulimall-auth-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  redis:
    host: 192.168.40.129
    port: 6379
  session:
    store-type: redis
server:
  port: 14000
  servlet:
    session:
      timeout: 30m
logging:
  level:
    com.gulimall: error